### ISSUE TITLE
Form allows submission when DriverCollectionRadius is zero

### ISSUE THREAD

**Issue by jkbits1** [voteamerica/voteamerica.github.io#107]
Is this valid?

As I'm checking for it now in the node app, I want to sanitise to a sensible default.

**Comment by sasjkia** [comment]
I think so... it's the radius from the zip code - so i think the person would only be collecting in their own zip?

perhaps others could also wade in?

**Comment by sasjkia** [comment]
but we'll be changing the default to a wider radius / or to blank ad then force an entry

**Comment by dmilet** [comment]
Setting the radius to a large value (like 50 miles) will artificially increase the limit of proposed matches, which might be irritating, because the list might get quite long.
I'd rather have a default of 0, thereby giving the highest scores within the driver's zip. Additional matches will be proposed, with a lowered rank.

**Comment by sasjkia** [comment]
@dmilet agreed. Or set to blank, to force people to think about it or select a value.

**Comment by jkbits1** [comment]
If it matches, then I'm much more relaxed about the default value. Still, to me zero suggests nothing happening from a UI point of view, whereas 1 or 2 has a clearer meaning. 

What do our US contributors think? In the UK, 50 miles seems quite far, in the US it's considered much nearer (but still a bit of trip I'd think).
