### ISSUE TITLE
Match didn't show up

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#110]
uuid
rider:c915e667-af66-46d2-a4e3-a274dd471295
driver:9c5f337f-3f22-458a-bc3e-8c17e81317d5

entered same variables as the ones tested just after 7pm bst. worked first time. when tried again just after 8pm (zip code 24540 for rider and 24541 for driver)

rider showed up in matching database but not driver.

**Comment by dmilet** [comment]
Acknowledged.
2nd rider was matched with 1st driver, and 2nd driver was starved, because all ride requests were matched to the 1st driver.

I'll fix it in the next revision.

carpool=# select * from nov2016.match
carpool-# ;
  state   |             uuid_driver              |              uuid_rider              | score 
----------+--------------------------------------+--------------------------------------+-------
 Proposed | be82961a-fc7e-40ac-8500-8086a17aef89 | 999b3eee-3da8-421c-81b9-897276bfe20a |   396
 Proposed | be82961a-fc7e-40ac-8500-8086a17aef89 | 80f67c9e-6be1-4b50-a93b-1fa20d2a6a43 |   400
 Proposed | 249aca4a-b08e-455c-826c-e5528131423b | 38294af1-76e2-464f-ad9b-a1fa00a4993e |   396
 Proposed | 249aca4a-b08e-455c-826c-e5528131423b | f3d5f1ae-a03c-44d9-a2a0-493dbf12a7a9 |   400
 Proposed | 249aca4a-b08e-455c-826c-e5528131423b | c915e667-af66-46d2-a4e3-a274dd471295 |   400
(5 rows)
