### ISSUE TITLE
Phone number format validation

### ISSUE THREAD

**Issue by dmilet** [voteamerica/voteamerica.github.io#111]
@sasjkia was suggesting we use the phone number as verification method when a user wants to cancel his/her drive offer or ride request. The phone number will be matched with the UUID that the user is supposed to know.
If the backend must perform validation on the phone number, we should enforce a syntax for phone number on the user interface. For example xxx-xxx-xxxx

**Comment by richardwestenra** [comment]
I would recommend not forcing people to follow an unfamiliar syntax when entering their phone numbers in the form. I've never encountered a form that requires me to enter dashes.

When performing validation (on the front or back end), we should err on the side of allowing false negatives (invalid phone numbers) rather than preventing users from entering a genuine human-readable phone number. If there are differences in format (e.g. users adding numbers or spaces) then we can sanitise our inputs by removing any non-numerical characters (except for `x` and `+`) later on.

There's some useful info in this stackoverflow thread: http://stackoverflow.com/questions/123559/a-comprehensive-regex-for-phone-number-validation

How does that sound to you?

**Comment by dmilet** [comment]
Sanitize is ok of course, as long as we have a consistent way of doing it, so that we are able to match the phone number when it's used for verification purposes. I'll leave it to the front end experts to decide what's the best way to achieve it.

**Comment by richardwestenra** [comment]
@dmilet Are you happy for me to close this issue? I'm not sure that anything more needs to be done on the front end, unless you really wanna push for some phone number format validation.

**Comment by dmilet** [comment]
We can close the issue now. I'm using  pattern matching to validate phone number when needed at the backend. No need to do special validation on the user form.
