### ISSUE TITLE
YouTube link is broken

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#112]
Doesn't lead anywhere when clicked.

Format strange upon hover.

**Comment by richardwestenra** [comment]
That is super weird! That wasn't at all how it was behaving when I added it. I wonder whether they just updated it yesterday? :(

💩 okay I'll look into it. Worst case scenario, I'll need to remove it or roll my own.

**Comment by richardwestenra** [comment]
If anyone else wants to give this a shot, go ahead, else I'll get to it when I can. If we can make the button work properly again, great, else I'm tempted to just make our own button in the exact same style as the existing youtube button (e.g. see below)
![image](https://cloud.githubusercontent.com/assets/1155816/19458403/b7e3d094-94c3-11e6-9e3f-970dbc895a2c.png)

See #93 for details about the original task and #104 for the PR that created this button.

**Comment by sasjkia** [comment]
that works - as long as edges are rounded

**Comment by valterlima** [comment]
Got this error message:

> Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://www.youtube.com') does not match the recipient window's origin ('https://www.youtube.com').

**Comment by richardwestenra** [comment]
@valterlima Yeah I've noticed that same issue. I did a lot of googling and experimentation but nothing I've tried has worked. I think the only thing for it is to make our own HTML/CSS button.

**Comment by Jason9199** [comment]
While there is an error in the console, the button is working perfectly for me.

**Comment by srMarquinho** [comment]
It seems a to be Youtube issue. It is working on Google Chrome but not on Firefox.
The code is correct here and I may try an alternative solution.
You can try and have a go to check if the feature works for you here: https://developers.google.com/youtube/youtube_subscribe_button

**Comment by suamorales** [comment]
Works fine for me. OSx & Chrome 53

**Comment by sasjkia** [comment]
It's now working fine for me on Chrome 53. Still slightly strange formatting upon hover... Will check again when I get to work.

**Comment by dmilet** [comment]
If the page is loaded from https, the http Youtube link will be blocked.
Since we're normally not loaded the main page over https , it should not be a problem, unless maybe from the Thank you page since the post when to https://api.carpoolvote.com
Better to use https for the youtube link anyway

The page at 'https://api.carpoolvotye.com/www/v2.0/' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/subscribe_embed?channelid=UCY1aS3TMDGxVbckA7Va0QFA&a…res__%2Fam%3DAQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAGLTcCPuU6WIrjNlyvXhx28tkKfenwRCSQ'. This request has been blocked; the content must be served over HTTPS.
