### ISSUE TITLE
Screen-reader friendly banner box titles

### ISSUE THREAD

**Issue by langdonms** [voteamerica/voteamerica.github.io#129]
When tabbing through the website using the built in Windows screen reader, the tab readings skip from  "I need a ride", "I can offer a ride," straight to the "Name" "Email" forms on the "Can I help in some other way" volunteer box. This would be confusing if you thought that was the signup form as a rider/driver and not the volunteer form. Propose making the banner titles tab-able so visually impaired know which box they are currently in.

**Comment by richardwestenra** [comment]
I don't believe it's necessary to make something tab-able in order to make them readable for visually impaired users, because an experienced screenreader user won't just be using tab to navigate - they can also browse any other properly marked-up content on the page, e.g. headings, paragraphs, etc.

However you raise a very good point! The accessibility on this site is woeful, and there are some simple steps to improve it. A good quick fix would be to add `aria-controls` attributes on the two form buttons to indicate to which section they refer, and to toggle `aria-hidden` on the two main signup forms. 

Thanks for flagging this!
