### ISSUE TITLE
Driver prevents form submit with invalid collection zip code but does not highlight as error

### ISSUE THREAD

**Issue by jkbits1** [voteamerica/voteamerica.github.io#134]
all this is FYI btw, but probably can confuse user (comments while checking https://github.com/voteamerica/voteamerica.github.io/pull/128)

on submitting with no fields collection zip is not shown as red. page does not scroll automatically to collection zip
on submit with empty date/times and empty collection, screen pauses at submit button. not clear there is an error.
finally, added date/time, and clicked submit. screen pauses at submit button. collection zip is empty but not red. it is not clear there is an error.

**Comment by lhmzhou** [comment]
My screen also pauses. A glitch possibly?

**Comment by richardwestenra** [comment]
ooh, good catch! I think this is due to two different issues:

1. On the driver form, there are two input fields (zip code and radius) within the same `form-group` row. We should separate these into two different rows.

2. I think the screen scroll glitch is because the hiddenJSONTimes text input is set to display:none. This can be fixed by hiding it a different way, e.g.
```
.hiddenJSONTimes {
    position: absolute;
    pointer-events: none;
    opacity: 0;
    margin-top: -100px;
}
```

**Comment by jkbits1** [comment]
great, thanks @richardwestenra :+1:
