### ISSUE TITLE
Message after DRIVER form submitted is for RIDERS

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#182]
Haven't tested message for RIDER forms. See #131

**Comment by misteranderson** [comment]
This is because the driver form is configured to redirect to the thanks-rider page, and the rider form is configured to redirect to the thanks-driver page.

Current:
<form id="offer-ride" name="offerRide" action="https://api.carpoolvote.com/live/**driver**" method="post" class="ride-form" role="form" aria-hidden="true">
<input type="hidden" name="_redirect" class="redirect" value="http://carpoolvote.com/**thanks-rider**/" />

<form id="need-ride" name="needRide" action="https://api.carpoolvote.com/live/**rider**" method="post" class="ride-form" role="form" aria-hidden="true">
<input type="hidden" name="_redirect" class="redirect" value="http://carpoolvote.com/**thanks-driver**/" />

**Comment by richardwestenra** [comment]
This is almost definitely my fault. I'll take it. Thanks for spotting @sasjkia @misteranderson.
