### ISSUE TITLE
Add multiple date and time picker to driver and rider signup forms

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#19]
In the I NEED A RIDE form, change the date language to: When could you travel?
Hover text: Select all dates and times that would work for your ride. We'll let you know when there will be a driver available.

To allow the user to pick dates/times, use the graphic appearance attached. The user should be able to select multiple (nonconsecutive) dates and should be required to select time slots for each date, before being able to select the next date. They should also be able to select multiple (nonconsecutive) time slots for each date.

Example of a multiple date picker: [https://arca-computing.github.io/MultipleDatePicker/](url)
Example of a date and time picker (this doesn't allow for multiple date/time selection but otherwise has a good interface): [https://arca-computing.github.io/MultipleDatePicker/](url)

Repeat this process in the I CAN OFFER A RIDE form. Use the following text:
When will you be available to give a ride?
Hover text: You can select multiple dates or/and timeframes, if you're available for more than one ride.

>
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/19363959/18368202/b8068e52-7616-11e6-8965-c4275f5effc5.jpg)

**Comment by sfirrin** [comment]
I mentioned I could work on this but I think doing it exactly to these specs would require a time commitment / level of skill outside of what I have. The multiple picker that you linked unfortunately only works for Angular apps.

What I can do, and what might even be a better UX solution, is to have three date picker input boxes that they can fill (only require them to fill one), and then a button for them to ask for more date picker inputs. Something like this: 

![image](https://cloud.githubusercontent.com/assets/13263282/18610292/35ae077e-7ce6-11e6-80c0-0f0699152b2f.png)

Let me know if you'd like me to do this.

**Comment by sasjkia** [comment]
Thanks for working on this @sfirrin! This could work... Remember that we need time slots, not just times. And someone may enter multiple time slots per date (i.e., in the morning on the way to work and in the afternoon on the way back). As long is it has this functionality, it makes sense to go ahead with the version you have recommended. :)

**Comment by sfirrin** [comment]
Oh right I forgot it had to be a range. I can imagine doing something like this:
![image](https://cloud.githubusercontent.com/assets/13263282/18610512/48d04906-7cec-11e6-8bee-df22e5d16b9c.png)

It seems like it would just be relatively minor changes to this jQuery plugin (the one you screenshotted in the issue): http://xdsoft.net/jqplugins/datetimepicker/

**Comment by sasjkia** [comment]
Ok - though remember that some people might be driving all day on multiple days. Is this the most intuitive way for this kind of user to interact with the interface?

**Comment by sfirrin** [comment]
Hmm it's probably going to be a pain for the users who are driving multiple days. Not sure if there's a way around that though since they'll still need to specify the date, start, and end times that they're available. I could imagine an "All day" option that would select something like 8am to 10pm for them. 

Do you have any ideas? (I am pretty far from a UX designer)

**Comment by sasjkia** [comment]
If you cannot select multiple time slots visually, the user could just input a start and an end time, and can have the option of adding more time slots for the same date

**Comment by sfirrin** [comment]
That might be best

**Comment by sasjkia** [comment]
alrighty 👍

**Comment by sfirrin** [comment]
Hey I've been working on this in this branch here: https://github.com/voteamerica/voteamerica.github.io/tree/develop_calendar

I wasn't really satisfied with my original plan and I had the idea of having the datepicker and time range slider be fixed, and the user changing them accordingly in order to add the currently selected options to a list of datetimes. It looks like this:
![image](https://cloud.githubusercontent.com/assets/13263282/18620654/dda4236a-7de4-11e6-96b4-da440ba5ab45.png)
The styles can use some work and the remove button needs to be implemented but otherwise it works. Let me know what you think.

**Comment by sfirrin** [comment]
Oh and the button will update with the currently selected date and time range also but I haven't gotten to that quite yet.

**Comment by sasjkia** [comment]
I think this is good - thank you! Can you select the same date twice? (in case people want to do morning before work and evening after work).

**Comment by sfirrin** [comment]
Yep you can select as many times on the same date as you want.

**Comment by sfirrin** [comment]
I just submitted a pull request.

**Comment by sasjkia** [comment]
@sfirrin could I check, has your work on this also incorporated issue #18?
