### ISSUE TITLE
Driver Thanks page does not link to self-service page correctly

### ISSUE THREAD

**Issue by jkbits1** [voteamerica/voteamerica.github.io#198]
When the self-service page is accessed from the Driver Thank you page, the wrong param is sent (uuid, not UUID_driver). The confirmation field is shown but there is not Login button.

The self service page is not usable

I'm assuming these things are connected but happy to help resolve the issue whatever the cause

**Comment by richardwestenra** [comment]
This is intentional. Given that some sources provide the key `UUID` and others (though none that I've seen) apparently provide `UUID_Driver` etc, I've resolved these into just using UUID at the moment on the selfservice page. Hence the UUID link [should work fine with the updates](http://richardwestenra.com/voteamerica.github.io/self-service/?type=driver&uuid=1234567890&score=1) in #196.

If you use a URL with `score` in it (e.g. http://richardwestenra.com/voteamerica.github.io/self-service/?type=driver&uuid=1234567890&score=1), then you should see these extra buttons. This is because the score parameter is required in order to send a request to those endpoints, from what I could tell from looking at your code. However, I have not yet seen a scenario where a user would receive a link with the 'score' query string populated, so there's no real world scenario where those buttons are currently usable, so the point is moot.

If those extra values are not necessary then we can remove them from the AJAX request parameters, and show the buttons after all. Else, if we have an endpoint to look them up, then we can retrieve that value and show the buttons. Else, it's pointless.

**Comment by langdonms** [comment]
@richardwestenra @jkbits1 I experienced same issue: , created test rider/users and had same experience - both SMS and email Thank You confirmations had self-service urls with lowercase parameter `UUID`s resulting in no action buttons available. @misteranderson clarified this was due to the needed format of capital `UUID` and as you identified above. 

Example received in both SMS and email Mon, Oct 31, 2016 at 8:43 PM (EST)
http://carpoolvote.com/self-service/?uuid_driver=a565882a-175a-41b3-aed3-ba0bac42e67f

**Comment by jkbits1** [comment]
@richardwestenra I've created some changes to the relevant db code. These have been applied to the test db and a test match created. The querystring parameters have been checked in the emails and are correct now. 

You are correct that the existing code does not always provide the Score param correctly. This has been amended in some cases but some gaps remain.

If you can revise the PR to work against the test db then the relevant db changes can be made to the live db and the PR deployed. After that we can decide what further functionality is required for the self service page

**Comment by richardwestenra** [comment]
ah yeah I see, the old emails I was receiving were using `uuid` but I just submitted the form again and received one in the following format: `http://carpoolvote.com/self-service/?UUID_rider=352a57f8-b4d5-43dd-8ba3-8d43591723b8`
This should work fine with yesterday's updates to #196, however.

**Comment by richardwestenra** [comment]
@jkbits1 Sorry, I'm not following you. Where does a user get a URL with the score value added? In emails?

If a user is arriving at this site via the thank you page and only has the UUID/UUID_Rider parameter, is there a way for them to retrieve the values they need in order to view/edit/cancel/accept matches? Users should be able to log in from anywhere, as long as they have their reference number (which we asked them to save, and which was emailed to them), and their phone number.

**Comment by jkbits1** [comment]
@richardwestenra hi. btw thanks for a thorough response in your first comment on this issue.

That's right, the links are in the emails and sms messages. At the moment, methods only exist for some of the paths the users take. However, if we get these parts working, then we can resolve those.

I have had to make revisions to the db code, which exist on the test system. I haven't checked this PR against the test system. Can you check the PR behaves as you expect on the test system first, please?

**Comment by sasjkia** [comment]
Glad to see that this is taking shape!

Apologies if I'm not following correctly but what are planned steps for this? What's the difference between the CANCEL RIDE REQUEST and CANCEL RIDER MATCH REQUEST buttons?

**Comment by jkbits1** [comment]
@sasjkia good question. The names are from the user stories document, and get shortened to become db  functions and node app routes. Cancel ride request is a complete exit from the system by the rider, which cancel match request cancels a single match (made when the driver accepts a proposal)

**Comment by sasjkia** [comment]
@jkbits1 thanks a lot! could we please change the button text to REJECT CURRENT RIDE OFFER?

**Comment by jkbits1** [comment]
The thanks pages don't display the uuid and do not provide a valid link to the self service page. 

This is resolved by https://github.com/voteamerica/voteamerica.github.io/pull/209
