### ISSUE TITLE
Signup form updates

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#267]
Please also liaise with backend, as required for the below

- [x] On both signup forms, changes "Dates available" to "Dates and times available"
- [x] On driver signup form, change "Pickup zip code" to "Driving zip code"
- [x] ~On both signup forms, force user to open terms and conditions before checking the box stating that they agree.~
- [x] On rider signup form, change "Your trip" heading to "Dates and times available", and delete "Dates and times available subheading. (Because the sections below this also refer to the trip)
- [ ] On rider signup form, make "Your trip" a larger section that includes the dates, location, and vehicles sections. Underneath the "Your trip" heading, add explanation text "Our automatic matching algorithm will use this information to try to find you a driver".
- [ ] On the rider signup form, give the "Your details" section style the same style as the "Your trip" section (in the point above). Underneath the heading, add explanatory text: "The driver will automatically receive these details once there's a confirmed match."
- [ ] On the driver signup form, make "What can you offer" a larger section that includes the dates, and location and vehicles sections. Underneath the "What can you offer" heading, add explanation text "Our automatic matching algorithm will use this information to try to find you voters who need a ride".
- [ ] On the driver signup form, give the "Your details" section heading the same style as the "Your trip" section (in the point above). Underneath the heading, add explanatory text: "The rider will automatically receive these details once you have confirmed a suggested match."
- [x] On rider signup form, change "We'll record these details and contact you if someone can help." to "Our system will use these details to try to find you a driver. If there is a match, the driver will get in touch to arrange the ride".
- [x] On driver signup form, change "We'll record these details and contact you if there's a match." to "Our system will use these details to try to find riders. If there is a potential match, we'll send you a notification. If you accept the match, we'll let the rider know that you'll be in touch to arrange the ride."
- [ ] On rider signup form collection address, separate the street/apartment numbers from the street names (these should be separate entries in the database)
- [x] For the rider signup form, add address verification
- [ ] For the driver signup form, add zip code verification

**Comment by russon77** [comment]
@sasjkia i'm interested in doing the easy text edits/display changes. has this been assigned yet?

**Comment by sasjkia** [comment]
@russon77 that's great - thank you! it's been been assigned so please go ahead. please also coordinate with @dmilet regarding separating the street/apartment numbers from the address, as this may be better to do on the backend.

**Comment by russon77** [comment]
thanks @sasjkia . could you explain what you mean by the following, possibly with examples?

-    For the rider signup form, add address verification
	
-    For the driver signup form, add zip code verification

**Comment by sasjkia** [comment]
@russon77 we want to ensure that people are submitting a real address and zip code (we saw a few mistakes in the data before). Even better if the address has an autocomplete function, so people don't have to type out the whole thing.

This is a bit more advanced than the other points.

**Comment by sasjkia** [comment]
@russon77 e.g., https://developers.google.com/maps/documentation/javascript/places-autocomplete

**Comment by richardwestenra** [comment]
A note regarding the third point: I think we need to discuss the UX implications of adding this feature. I'd argue that this might negatively affect users and possibly prevent some users from successfully completing the form. It's a user-hostile feature, and we should only add it if it's legally required.

**Comment by russon77** [comment]
thanks @richardwestenra :+1: 

i have created a basic fix for the section changes, let me know if its okay and i'll change the driver signup and PR:

![updated_sections](https://cloud.githubusercontent.com/assets/17035732/26213565/928d93ba-3bc7-11e7-8224-4059ac0e3508.png)

**Comment by russon77** [comment]
@sasjkia what do you think of the design? i kept it minimal

**Comment by richardwestenra** [comment]
@russon77 What browser/OS are you testing this in? I would also check any changes in Chrome, because it looks like you're viewing the fallback date/time inputs.

Regarding the design, I'd get rid of the horizontal rule under "Our automatic matching algorithm will use this information to try to find you a driver".

**Comment by richardwestenra** [comment]
For what it's worth, I don't think the 'Your trip' header is necessary either. I'm also not sure we need the "Our automatic matching algorithm will use this information to try to find you a driver" paragraph.

@sasjkia What's the rationale for these additions?

**Comment by sasjkia** [comment]
@richardwestenra agreed. But does the matching Our automatic matching algorithm will use this information to try to find you a driver" bit still appear at the bottom? This needs to be included because there are a lot of questions about it.

**Comment by richardwestenra** [comment]
Okay cool, thanks @sasjkia! In that case, I would just include the following paragraph, above the first form section:
> Please enter your details in the form below, and our automatic matching algorithm will use this information to try to find you a driver.

like so:
![image](https://cloud.githubusercontent.com/assets/1155816/26252708/e98f2cb4-3ca8-11e7-9e30-531d805d5fce.png)

**Comment by russon77** [comment]
@sasjkia currently on http://carpoolvote.com/#need-ride at the end of the rider signup form, the text is

> What happens next? Our system will use these details to try to find you a driver. If there is a match, the driver will get in touch to arrange the ride.

is this enough?

for the zip code verification, there's already some level of validation - `Please match the requested format.` did you have something else in mind?

lastly, for the address verification - is it required that the address be selected from the google address search? are we trusting that google has effectively indexed every location in america? for example, rural voters ( who may be at an increased risk of not having access to transportation ) may not be able to specify their location. just a thought, happy to implement though!

**Comment by richardwestenra** [comment]
@sasjkia I'd be very wary of overly-aggressive form input validation. Far better to accept invalid form data than prevent someone from completing the form with valid details.

**Comment by sasjkia** [comment]
@richardwestenra noted. Is there a way to let people override if their address doesn't show up?

**Comment by richardwestenra** [comment]
@sasjkia Sorry, if their address doesn't show up where? I don't understand.

**Comment by sasjkia** [comment]
@richardwestenra the address, in the system.

**Comment by richardwestenra** [comment]
@sasjkia Override how? Sorry, I'm still really confused about what sort of situation you're describing.

**Comment by russon77** [comment]
@richardwestenra @sasjkia is talking about the google address autocomplete - it provides a selectable drop-down to a text input, so that the user can select a pre-validated address.

i think verification by google should be optional. maybe a voter does not want to supply their address to vote america and would prefer to communicate directly with the driver after being matched based on the relative area. or like i said, maybe their address isn't in google's database.

i will move forward with adding the google address autocomplete, but i will not require that the address be sourced from there. also any news on the requested text updates? not sure what was finalized.

**Comment by sasjkia** [comment]
thanks @russon77! what are you waiting on re text updates?

**Comment by russon77** [comment]
should i add the text, like shown in https://github.com/voteamerica/voteamerica.github.io/issues/267#issuecomment-302720227

or is the text at the bottom of signup enough?

> What happens next? Our system will use these details to try to find you a driver. If there is a match, the driver will get in touch to arrange the ride.

**Comment by russon77** [comment]
@sasjkia for the autocomplete functionality, i need a google API key. the limit is 1k requests per day, but can be increased for free by adding a credit card to the account to 150k requests per day. you can get an API key with your/voteamerica's google account here: https://developers.google.com/places/web-service/usage#enable_billing

source:

https://developers.google.com/maps/documentation/javascript/places-autocomplete

if we don't want to use google, there are other services available - however they would require additional work.

**Comment by sasjkia** [comment]
@russon77 please could you check with @kyle in the slack? he's taking over ux and will be better placed to make the call :)

**Comment by richardwestenra** [comment]
btw @russon77 which issues (if any) have you completed locally, and which are you currently working on?
Feel free to break this issue into multiple PRs, so that we can ship early and often, and to keep our review workload relatively manageable. (See: [Reviewing a small PR versus reviewing a large one](https://www.youtube.com/watch?v=Q5b_0bulGi4))

**Comment by russon77** [comment]
@richardwestenra i have broken the issue into several PRs already. i am currently working on the address autocomplete.

**Comment by richardwestenra** [comment]
@russon77 Oh yeah so you have, sorry, nevermind me. Thanks for the update!

**Comment by russon77** [comment]
@sasjkia correct me if i'm wrong, but i believe that the only remaining change in this issue is:

- [ ]  On rider signup form collection address, separate the street/apartment numbers from the street names (these should be separate entries in the database)

is this still a requirement? i have some worries about the interaction with the google autocomplete - we would need 3 inputs instead of the current single input.

can i ask what this is intended to solve? perhaps there is another way! :laughing:

**Comment by sasjkia** [comment]
@russon77 good question! I'm trying to get to a point where we can send the rider's street name etc but not the exact house/apartment number. Reasoning is that we'd like to keep personal details to a minimum during the initial notification, which goes out to all potential drivers. Zip code is a little too wide of people to make an informed judgment about whether or not they can drive. I'm open to other suggestions - including finding a way to strip these out at the backend.

Perhaps @kylejcrawford, @richardwestenra, @jkbits1 also have some thoughts on this.

**Comment by russon77** [comment]
@sasjkia after matching, do the driver and rider have a direct line of communication? if so, we could ask only for the general area, like the street but not the house number. then, after a match, the driver and rider communicate and pick a mutually safe place to meet.

this is safer, because at no point does vote america know the specific address, so it can't be stolen and used for nefarious purposes. but it also increases the burden of the driver and rider, who have to communicate to pick a meeting location - but maybe they already do?

**Comment by sasjkia** [comment]
The address autocomplete is awesome - thank you!!! :)

**Comment by jkbits1** [comment]
@sasjkia these sub-issues have either been addressed already or are less relevant now the system is focused around operators

Thanks everyone 👍
