### ISSUE TITLE
Back-end - Organization registry

### ISSUE THREAD

**Issue by andrewcuan** [voteamerica/voteamerica.github.io#349]
As a field organizer, I want to be able to manage a list of organizations that the campaign works with in order to see what drivers and riders they are recruiting.
**Acceptance criteria** - for registry
- [ ] - Org ID (Auto-generated)
- [ ] - Organization name
**Additional acceptance criteria**
- [ ] - Org ID appears in drop down list for Org ID for the driver list and rider list after being created in original organization list

**Comment by jkbits1** [comment]
@acqsysandrea @aaghevli following our meeting, just pinging about these as discussed

**Comment by jkbits1** [comment]
There is a decision to be made related to this, that is, can all organisers see info for all organisations?

@stephenscapelliti without addressing the details of the issue as originally, so just on the question in this comment, what are your thoughts on what organisers are permitted to see?

**Comment by acqsysandrea** [comment]
I had an opportunity to login to the backend and take a look around. There is a lot more information than any operator every needs to see. We are also missing two critical pieces of information as organizations operate in multiple states. We need to see City and State. Zip code is necessary for the matching but it provides no human usable information.

Also will the map move to the backend. Here is how I use Carpool vote

When I have a ride request I look at the map and see if I have a driver in the City. If so, then there is a possibility that I have a driver for my rider. I also can use the map to see if I need to recruit drivers for a certain area because I have riders. That is how the map is extremely useful. In addition to having riders ready to upload directly into the system from multiple cities and states, operators will also be getting calls.

**Comment by jkbits1** [comment]
@acqsysandrea thanks for the feedback, I'll review it. I tried to initiate a discussion about these extra fields a few months ago with issue #359. The opportunity has probably passed now to have this functionality ready for the mid-terms

**Comment by jkbits1** [comment]
@andrewcuan features requested are either provided or will be revised for the current system behaviour

@acqsysandrea city and state are provided, map will not be enhanced but will remain
