### ISSUE TITLE
Add Home page navigation link and remove Support link

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#90]
To the left of the other navigation page links, add _Home_
People may want to return to the home page from whatever part of the site they're on

Remove the _Support_ link
No current plans for a separate pate

**Comment by richardwestenra** [comment]
idk, let's talk about this.
1. There is currently already a link to the homepage: It's the logo. This is common UI design practice and should be reasonably familiar to users.
2. We don't currently have any other pages in the site, really. We need to sort out form history/routing navigation because it's currently woeful, but that's a separate issue that I want to address.
3. We can remove the Support link but it currently links to a section on the homepage, as do the other nav links.

**Comment by sasjkia** [comment]
1. Ok - you're the expert :)
2. True. I had hoped to have some more pages (see other issues); this also helps with SEO.
3. Let's redo these links once the page/site layout is finalized?

**Comment by jkbits1** [comment]
Just commenting as I used the site for the first time when entering riders and drivers a few days ago so I came to the UI fresh.

It did feel slightly unintuitive and jarring to enter rider or driver info and then choosing to return to the main page. For me, this is because we have the logo in the middle and nothing in the top left corner, so I had to think consciously about clicking on the logo. Generally I think of something in the middle as a banner (not a suggestion to change anything btw). 

However, I also thought that as a user, I wouldn't be returning anywhere. Once I submit a ride/request offer, there's nothing else to do. It might be interesting to consider how the site navigation fits in with cancellation or things like that. I think this generally relates to point 2 in richard's comment
